### ISSUE TITLE
AK-1: pip install 'global-chem[all]' crashes 

### ISSUE THREAD

**Issue by anmolecule** [Global-Chem/global-chem#149]
Error message: 
error: subprocess-exited-with-error

```
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [12 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-oezw10nj/molpdf_fbac72933d574a05a3a38c685b851abb/setup.py", line 50, in <module>
          install_requires=_parse_requirements('requires.txt'),
        File "/tmp/pip-install-oezw10nj/molpdf_fbac72933d574a05a3a38c685b851abb/setup.py", line 28, in _parse_requirements
          return distutils.text_file.TextFile(filename=str(Path(__file__).with_name(filename))).readlines()
        File "/home/anmol/miniconda/envs/globalchem/lib/python3.10/site-packages/setuptools/_distutils/text_file.py", line 100, in __init__
          self.open(filename)
        File "/home/anmol/miniconda/envs/globalchem/lib/python3.10/site-packages/setuptools/_distutils/text_file.py", line 115, in open
          self.file = io.open(self.filename, 'r', errors=self.errors)
      FileNotFoundError: [Errno 2] No such file or directory: '/tmp/pip-install-oezw10nj/molpdf_fbac72933d574a05a3a38c685b851abb/requires.txt'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
```
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

Anmol:
```
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/pip-install-oezw10nj/molpdf_fbac72933d574a05a3a38c685b851abb/requires.txt' 
```
Should it search for requires.txt or requirements.txt

**Comment by Sulstice** [comment]
The distribution chain for all was super weird and maybe I didn't fully test it in the context of a colab. So that's a fault of mine. This needs to be resolve ASAP so moving into priority.

**Comment by Sulstice** [comment]
So here is the setup.py file:

```
    extras_require={
        'graphing': ['global-chem-extensions[graphing]'],
        'forcefields': ['global-chem-extensions[forcefields]'],
        'bioinformatics': ['global-chem-extensions[bioinformatics]'],
        'cheminformatics': ['global-chem-extensions[cheminformatics]'],
        'quantum_chemistry': ['global-chem-extensions[quantum_chemistry]'],
        'development_operations': ['global-chem-extensions[development_operations]'],
        'all': [
            'global-chem-extensions',
            'global-chem-extensions[graphing]',
            'global-chem-extensions[forcefields]',
            'global-chem-extensions[bioinformatics]',
            'global-chem-extensions[cheminformatics]',
            'global-chem-extensions[quantum_chemistry]',
            'global-chem-extensions[development_operations]',
        ]
    },
```

I think what needs to happen is the removal of the `global-chem-extensions` actually now that I look at it. That actually might be the issue. 

To this:

```
    extras_require={
        'graphing': ['global-chem-extensions[graphing]'],
        'forcefields': ['global-chem-extensions[forcefields]'],
        'bioinformatics': ['global-chem-extensions[bioinformatics]'],
        'cheminformatics': ['global-chem-extensions[cheminformatics]'],
        'quantum_chemistry': ['global-chem-extensions[quantum_chemistry]'],
        'development_operations': ['global-chem-extensions[development_operations]'],
        'all': [
            'global-chem-extensions[graphing]',
            'global-chem-extensions[forcefields]',
            'global-chem-extensions[bioinformatics]',
            'global-chem-extensions[cheminformatics]',
            'global-chem-extensions[quantum_chemistry]',
            'global-chem-extensions[development_operations]',
        ]
    },
```

**Comment by Sulstice** [comment]
Try it now, I think that fixed it. 

```
Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Collecting global-chem[all]
  Downloading global_chem-1.7.0.1.tar.gz (192 kB)
     |████████████████████████████████| 192 kB 5.3 MB/s 
Collecting global-chem-extensions
  Downloading global_chem_extensions-1.0.1.tar.gz (42 kB)
     |████████████████████████████████| 42 kB 727 kB/s 
Requirement already satisfied: numpy in /usr/local/lib/python3.7/dist-packages (from global-chem-extensions->global-chem[all]) (1.21.6)
Collecting rdkit-pypi
  Downloading rdkit_pypi-2022.3.4-cp37-cp37m-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (22.7 MB)
     |████████████████████████████████| 22.7 MB 62.0 MB/s 
Requirement already satisfied: pandas in /usr/local/lib/python3.7/dist-packages (from global-chem-extensions->global-chem[all]) (1.3.5)
Requirement already satisfied: requests in /usr/local/lib/python3.7/dist-packages (from global-chem-extensions->global-chem[all]) (2.23.0)
Collecting biopython
  Downloading biopython-1.79-cp37-cp37m-manylinux_2_5_x86_64.manylinux1_x86_64.whl (2.3 MB)
     |████████████████████████████████| 2.3 MB 33.0 MB/s 
Collecting dna_features_viewer
  Downloading dna_features_viewer-3.1.1-py3-none-any.whl (30 kB)
Collecting biopandas
  Downloading biopandas-0.4.1-py2.py3-none-any.whl (878 kB)
     |████████████████████████████████| 878 kB 43.7 MB/s 
Collecting pypdb
  Downloading pypdb-2.2-py3-none-any.whl (34 kB)
Requirement already satisfied: setuptools in /usr/local/lib/python3.7/dist-packages (from biopandas->global-chem-extensions->global-chem[all]) (57.4.0)
Requirement already satisfied: pytz>=2017.3 in /usr/local/lib/python3.7/dist-packages (from pandas->global-chem-extensions->global-chem[all]) (2022.1)
Requirement already satisfied: python-dateutil>=2.7.3 in /usr/local/lib/python3.7/dist-packages (from pandas->global-chem-extensions->global-chem[all]) (2.8.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.7/dist-packages (from python-dateutil>=2.7.3->pandas->global-chem-extensions->global-chem[all]) (1.15.0)
Requirement already satisfied: packaging in /usr/local/lib/python3.7/dist-packages (from dna_features_viewer->global-chem-extensions->global-chem[all]) (21.3)
Requirement already satisfied: matplotlib>=3 in /usr/local/lib/python3.7/dist-packages (from dna_features_viewer->global-chem-extensions->global-chem[all]) (3.2.2)
Requirement already satisfied: kiwisolver>=1.0.1 in /usr/local/lib/python3.7/dist-packages (from matplotlib>=3->dna_features_viewer->global-chem-extensions->global-chem[all]) (1.4.4)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.7/dist-packages (from matplotlib>=3->dna_features_viewer->global-chem-extensions->global-chem[all]) (0.11.0)
Requirement already satisfied: pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.1 in /usr/local/lib/python3.7/dist-packages (from matplotlib>=3->dna_features_viewer->global-chem-extensions->global-chem[all]) (3.0.9)
Requirement already satisfied: typing-extensions in /usr/local/lib/python3.7/dist-packages (from kiwisolver>=1.0.1->matplotlib>=3->dna_features_viewer->global-chem-extensions->global-chem[all]) (4.1.1)
Collecting partialsmiles
  Downloading partialsmiles-1.0-py3-none-any.whl (13 kB)
Collecting pysmiles
  Downloading pysmiles-1.0.1.tar.gz (34 kB)
Collecting deepsmiles
  Downloading deepsmiles-1.0.1-py2.py3-none-any.whl (12 kB)
Collecting selfies
  Downloading selfies-2.1.1-py3-none-any.whl (35 kB)
Collecting molvs
  Downloading MolVS-0.1.1.tar.gz (61 kB)
     |████████████████████████████████| 61 kB 407 kB/s 
Requirement already satisfied: flask in /usr/local/lib/python3.7/dist-packages (from global-chem-extensions->global-chem[all]) (1.1.4)
Requirement already satisfied: plotly in /usr/local/lib/python3.7/dist-packages (from global-chem-extensions->global-chem[all]) (5.5.0)
Collecting kaleido
  Downloading kaleido-0.2.1-py2.py3-none-manylinux1_x86_64.whl (79.9 MB)
     |████████████████████████████████| 79.9 MB 111 kB/s 
Requirement already satisfied: bokeh in /usr/local/lib/python3.7/dist-packages (from global-chem-extensions->global-chem[all]) (2.3.3)
Collecting molpdf
  Downloading molpdf-1.0.0.tar.gz (11 kB)
Collecting dimorphite_dl
  Downloading dimorphite_dl-1.3.2.tar.gz (18 kB)
Collecting scaffoldgraph
  Downloading ScaffoldGraph-1.1.2-py3-none-any.whl (77 kB)
     |████████████████████████████████| 77 kB 5.1 MB/s 
Requirement already satisfied: Jinja2>=2.9 in /usr/local/lib/python3.7/dist-packages (from bokeh->global-chem-extensions->global-chem[all]) (2.11.3)
Requirement already satisfied: pillow>=7.1.0 in /usr/local/lib/python3.7/dist-packages (from bokeh->global-chem-extensions->global-chem[all]) (7.1.2)
Requirement already satisfied: tornado>=5.1 in /usr/local/lib/python3.7/dist-packages (from bokeh->global-chem-extensions->global-chem[all]) (5.1.1)
Requirement already satisfied: PyYAML>=3.10 in /usr/local/lib/python3.7/dist-packages (from bokeh->global-chem-extensions->global-chem[all]) (3.13)
Requirement already satisfied: MarkupSafe>=0.23 in /usr/local/lib/python3.7/dist-packages (from Jinja2>=2.9->bokeh->global-chem-extensions->global-chem[all]) (2.0.1)
Requirement already satisfied: click<8.0,>=5.1 in /usr/local/lib/python3.7/dist-packages (from flask->global-chem-extensions->global-chem[all]) (7.1.2)
Requirement already satisfied: itsdangerous<2.0,>=0.24 in /usr/local/lib/python3.7/dist-packages (from flask->global-chem-extensions->global-chem[all]) (1.1.0)
Requirement already satisfied: Werkzeug<2.0,>=0.15 in /usr/local/lib/python3.7/dist-packages (from flask->global-chem-extensions->global-chem[all]) (1.0.1)
Collecting moly
  Downloading moly-0.2.1-py3-none-any.whl (98 kB)
     |████████████████████████████████| 98 kB 8.1 MB/s 
Collecting epam.indigo==1.4.0b0
  Downloading epam.indigo-1.4.0b0-py3-none-manylinux1_x86_64.whl (11.5 MB)
     |████████████████████████████████| 11.5 MB 40.8 MB/s 
Collecting numpy
  Downloading numpy-1.18.3-cp37-cp37m-manylinux1_x86_64.whl (20.2 MB)
     |████████████████████████████████| 20.2 MB 60.0 MB/s 
Collecting opencv-python==4.2.0.34
  Downloading opencv_python-4.2.0.34-cp37-cp37m-manylinux1_x86_64.whl (28.2 MB)
     |████████████████████████████████| 28.2 MB 55.5 MB/s 
Collecting pdfminer==20191125
  Downloading pdfminer-20191125.tar.gz (4.2 MB)
     |████████████████████████████████| 4.2 MB 32.0 MB/s 
Collecting pdfrw==0.4
  Downloading pdfrw-0.4-py2.py3-none-any.whl (69 kB)
     |████████████████████████████████| 69 kB 7.3 MB/s 
Collecting pillow>=7.1.0
  Downloading Pillow-7.1.1-cp37-cp37m-manylinux1_x86_64.whl (2.1 MB)
     |████████████████████████████████| 2.1 MB 38.5 MB/s 
Collecting pycryptodome==3.9.7
  Downloading pycryptodome-3.9.7-cp37-cp37m-manylinux1_x86_64.whl (13.7 MB)
     |████████████████████████████████| 13.7 MB 6.0 MB/s 
Collecting reportlab==3.5.42
  Downloading reportlab-3.5.42-cp37-cp37m-manylinux2010_x86_64.whl (2.6 MB)
     |████████████████████████████████| 2.6 MB 39.7 MB/s 
Collecting six>=1.5
  Downloading six-1.14.0-py2.py3-none-any.whl (10 kB)
Collecting qcelemental
  Downloading qcelemental-0.25.0-py3-none-any.whl (334 kB)
     |████████████████████████████████| 334 kB 72.4 MB/s 
Requirement already satisfied: tenacity>=6.2.0 in /usr/local/lib/python3.7/dist-packages (from plotly->global-chem-extensions->global-chem[all]) (8.0.1)
Collecting pbr
  Using cached pbr-5.9.0-py2.py3-none-any.whl (112 kB)
Requirement already satisfied: networkx~=2.0 in /usr/local/lib/python3.7/dist-packages (from pysmiles->global-chem-extensions->global-chem[all]) (2.6.3)
Collecting pint>=0.10.0
  Downloading Pint-0.18-py2.py3-none-any.whl (209 kB)
     |████████████████████████████████| 209 kB 61.2 MB/s 
Requirement already satisfied: pydantic>=1.8.2 in /usr/local/lib/python3.7/dist-packages (from qcelemental->moly->global-chem-extensions->global-chem[all]) (1.8.2)
Requirement already satisfied: importlib-metadata in /usr/local/lib/python3.7/dist-packages (from pint>=0.10.0->qcelemental->moly->global-chem-extensions->global-chem[all]) (4.12.0)
Requirement already satisfied: zipp>=0.5 in /usr/local/lib/python3.7/dist-packages (from importlib-metadata->pint>=0.10.0->qcelemental->moly->global-chem-extensions->global-chem[all]) (3.8.1)
Requirement already satisfied: chardet<4,>=3.0.2 in /usr/local/lib/python3.7/dist-packages (from requests->global-chem-extensions->global-chem[all]) (3.0.4)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in /usr/local/lib/python3.7/dist-packages (from requests->global-chem-extensions->global-chem[all]) (1.24.3)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.7/dist-packages (from requests->global-chem-extensions->global-chem[all]) (2022.6.15)
Requirement already satisfied: idna<3,>=2.5 in /usr/local/lib/python3.7/dist-packages (from requests->global-chem-extensions->global-chem[all]) (2.10)
Requirement already satisfied: tqdm in /usr/local/lib/python3.7/dist-packages (from scaffoldgraph->global-chem-extensions->global-chem[all]) (4.64.0)
Requirement already satisfied: scipy>=1.3.1 in /usr/local/lib/python3.7/dist-packages (from scaffoldgraph->global-chem-extensions->global-chem[all]) (1.7.3)
Collecting loguru
  Downloading loguru-0.6.0-py3-none-any.whl (58 kB)
     |████████████████████████████████| 58 kB 5.5 MB/s 
Requirement already satisfied: pytest in /usr/local/lib/python3.7/dist-packages (from scaffoldgraph->global-chem-extensions->global-chem[all]) (3.6.4)
Requirement already satisfied: atomicwrites>=1.0 in /usr/local/lib/python3.7/dist-packages (from pytest->scaffoldgraph->global-chem-extensions->global-chem[all]) (1.4.1)
Requirement already satisfied: py>=1.5.0 in /usr/local/lib/python3.7/dist-packages (from pytest->scaffoldgraph->global-chem-extensions->global-chem[all]) (1.11.0)
Requirement already satisfied: attrs>=17.4.0 in /usr/local/lib/python3.7/dist-packages (from pytest->scaffoldgraph->global-chem-extensions->global-chem[all]) (21.4.0)
Requirement already satisfied: pluggy<0.8,>=0.5 in /usr/local/lib/python3.7/dist-packages (from pytest->scaffoldgraph->global-chem-extensions->global-chem[all]) (0.7.1)
Requirement already satisfied: more-itertools>=4.0.0 in /usr/local/lib/python3.7/dist-packages (from pytest->scaffoldgraph->global-chem-extensions->global-chem[all]) (8.13.0)
Building wheels for collected packages: global-chem, global-chem-extensions, dimorphite-dl, molpdf, pdfminer, molvs, pysmiles
  Building wheel for global-chem (setup.py) ... done
  Created wheel for global-chem: filename=global_chem-1.7.0.1-py3-none-any.whl size=224705 sha256=bfd06a37195dda3ca7207a9f89a60d1ad12cc22b5eebe93b4a984964b82ce90e
  Stored in directory: /root/.cache/pip/wheels/8b/29/0e/dfe71e3dd5eacd7bde245fda255c4a2b5326b95d5dcff7761f
  Building wheel for global-chem-extensions (setup.py) ... done
  Created wheel for global-chem-extensions: filename=global_chem_extensions-1.0.1-py3-none-any.whl size=62619 sha256=384e41abec374af20d8de63ca19007ca75432dee4a32ec7db1be311a68b4434c
  Stored in directory: /root/.cache/pip/wheels/31/a8/bd/b8886e29ec09c111ca89ca0595289afbd5fa63e3b63bd1ef4b
  Building wheel for dimorphite-dl (setup.py) ... done
  Created wheel for dimorphite-dl: filename=dimorphite_dl-1.3.2-py3-none-any.whl size=16892 sha256=acd3556a64a8a2e899f2789a36c6d77f1ad6ca56d5320d6075eb8598c392c44c
  Stored in directory: /root/.cache/pip/wheels/b3/51/be/0256a36265d9f29bd02c78390273277187b0df441f0fa09358
  Building wheel for molpdf (setup.py) ... done
  Created wheel for molpdf: filename=molpdf-1.0.0-py3-none-any.whl size=8520 sha256=071534a747e5974f9310db3ad0c44c610b082b62575e1a15c57f6845f6ccc141
  Stored in directory: /root/.cache/pip/wheels/52/ca/ee/cdb5661250272e1fdd691e8a19c68d2388c79221c7ed1296a7
  Building wheel for pdfminer (setup.py) ... done
  Created wheel for pdfminer: filename=pdfminer-20191125-py3-none-any.whl size=6140106 sha256=c0e2c9a31c279cf319dabbb1e908f1795dadd7a61a4f39e6c363a4e8ce6af868
  Stored in directory: /root/.cache/pip/wheels/e3/5e/f4/d210b46e9e4a28229ea070ed5b3efa92c3c29d1a7918dd4b97
  Building wheel for molvs (setup.py) ... done
  Created wheel for molvs: filename=MolVS-0.1.1-py3-none-any.whl size=32387 sha256=07bf5506047e261ad1ae352c8bd04c962fbe0b06e67066640d3ef5052dcb28c5
  Stored in directory: /root/.cache/pip/wheels/c4/c2/92/e85190307603c2b3733d43e357abae2d1c66b609bfbba6200d
  Building wheel for pysmiles (setup.py) ... done
  Created wheel for pysmiles: filename=pysmiles-1.0.1-py2.py3-none-any.whl size=22028 sha256=0c67be43ad8b6868dba777b0bb6b2df829936010047e19fbcce666562b7dac97
  Stored in directory: /root/.cache/pip/wheels/e4/f0/ca/dae2e932684a6e26824d29cf5b6dadea7320e6fed036942972
Successfully built global-chem global-chem-extensions dimorphite-dl molpdf pdfminer molvs pysmiles
Installing collected packages: six, pycryptodome, pint, pillow, numpy, reportlab, rdkit-pypi, qcelemental, pdfrw, pdfminer, pbr, opencv-python, loguru, global-chem, epam.indigo, biopython, selfies, scaffoldgraph, pysmiles, pypdb, partialsmiles, moly, molvs, molpdf, kaleido, global-chem-extensions, dna-features-viewer, dimorphite-dl, deepsmiles, biopandas
  Attempting uninstall: six
    Found existing installation: six 1.15.0
    Uninstalling six-1.15.0:
      Successfully uninstalled six-1.15.0
  Attempting uninstall: pillow
    Found existing installation: Pillow 7.1.2
    Uninstalling Pillow-7.1.2:
      Successfully uninstalled Pillow-7.1.2
  Attempting uninstall: numpy
    Found existing installation: numpy 1.21.6
    Uninstalling numpy-1.21.6:
      Successfully uninstalled numpy-1.21.6
  Attempting uninstall: opencv-python
    Found existing installation: opencv-python 4.6.0.66
    Uninstalling opencv-python-4.6.0.66:
      Successfully uninstalled opencv-python-4.6.0.66
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
xarray-einstats 0.2.2 requires numpy>=1.21, but you have numpy 1.18.3 which is incompatible.
tensorflow 2.8.2+zzzcolab20220527125636 requires numpy>=1.20, but you have numpy 1.18.3 which is incompatible.
tables 3.7.0 requires numpy>=1.19.0, but you have numpy 1.18.3 which is incompatible.
scikit-image 0.18.3 requires pillow!=7.1.0,!=7.1.1,>=4.3.0, but you have pillow 7.1.1 which is incompatible.
kapre 0.3.7 requires numpy>=1.18.5, but you have numpy 1.18.3 which is incompatible.
jaxlib 0.3.14+cuda11.cudnn805 requires numpy>=1.19, but you have numpy 1.18.3 which is incompatible.
jax 0.3.14 requires numpy>=1.19, but you have numpy 1.18.3 which is incompatible.
```

Ignore that error that comes from jupyter notebook.

**Comment by anmolecule** [comment]
```
(globalchem) anmol@anmoleculenovo:~/mywork/global-chem$ pip install 'global-chem[all]'
Requirement already satisfied: global-chem[all] in /home/anmol/miniconda/envs/globalchem/lib/python3.10/site-packages (1.7.0.1)
Requirement already satisfied: global-chem-extensions[forcefields] in /home/anmol/miniconda/envs/globalchem/lib/python3.10/site-packages/global_chem_extensions-1.0-py3.10.egg (from global-chem[all]) (1.0)
Requirement already satisfied: numpy in /home/anmol/miniconda/envs/globalchem/lib/python3.10/site-packages (from global-chem-extensions[forcefields]->global-chem[all]) (1.22.3)
Requirement already satisfied: rdkit-pypi in /home/anmol/miniconda/envs/globalchem/lib/python3.10/site-packages/rdkit_pypi-2022.3.4-py3.10-linux-x86_64.egg (from global-chem-extensions[forcefields]->global-chem[all]) (2022.3.4)
Requirement already satisfied: pandas in /home/anmol/miniconda/envs/globalchem/lib/python3.10/site-packages/pandas-1.4.3-py3.10-linux-x86_64.egg (from global-chem-extensions[forcefields]->global-chem[all]) (1.4.3)
Requirement already satisfied: requests in /home/anmol/miniconda/envs/globalchem/lib/python3.10/site-packages/requests-2.28.1-py3.10.egg (from global-chem-extensions[forcefields]->global-chem[all]) (2.28.1)
Collecting biopython
  Using cached biopython-1.79.tar.gz (16.7 MB)
  Preparing metadata (setup.py) ... done
Collecting dna_features_viewer
  Using cached dna_features_viewer-3.1.1-py3-none-any.whl (30 kB)
Collecting biopandas
  Using cached biopandas-0.4.1-py2.py3-none-any.whl (878 kB)
Collecting pypdb
  Using cached pypdb-2.2-py3-none-any.whl (34 kB)
Collecting partialsmiles
  Using cached partialsmiles-1.0-py3-none-any.whl (13 kB)
Collecting pysmiles
  Using cached pysmiles-1.0.1.tar.gz (34 kB)
  Preparing metadata (setup.py) ... done
Collecting deepsmiles
  Using cached deepsmiles-1.0.1-py2.py3-none-any.whl (12 kB)
Collecting selfies
  Using cached selfies-2.1.1-py3-none-any.whl (35 kB)
Collecting molvs
  Using cached MolVS-0.1.1.tar.gz (61 kB)
  Preparing metadata (setup.py) ... done
Collecting flask
  Using cached Flask-2.1.3-py3-none-any.whl (95 kB)
Collecting plotly
  Using cached plotly-5.9.0-py2.py3-none-any.whl (15.2 MB)
Collecting kaleido
  Using cached kaleido-0.2.1-py2.py3-none-manylinux1_x86_64.whl (79.9 MB)
Collecting bokeh
  Using cached bokeh-2.4.3-py3-none-any.whl (18.5 MB)
Collecting molpdf
  Using cached molpdf-1.0.0.tar.gz (11 kB)
  Preparing metadata (setup.py) ... done
Collecting dimorphite_dl
  Using cached dimorphite_dl-1.3.2.tar.gz (18 kB)
  Preparing metadata (setup.py) ... done
Collecting scaffoldgraph
  Using cached ScaffoldGraph-1.1.2-py3-none-any.whl (77 kB)
Collecting moly
  Using cached moly-0.2.1-py3-none-any.whl (98 kB)
Collecting pyyaml==3.13
  Using cached PyYAML-3.13.tar.gz (270 kB)
  Preparing metadata (setup.py) ... done
Requirement already satisfied: setuptools in /home/anmol/miniconda/envs/globalchem/lib/python3.10/site-packages (from biopandas->global-chem-extensions[forcefields]->global-chem[all]) (61.2.0)
Requirement already satisfied: python-dateutil>=2.8.1 in /home/anmol/miniconda/envs/globalchem/lib/python3.10/site-packages/python_dateutil-2.8.2-py3.10.egg (from pandas->global-chem-extensions[forcefields]->global-chem[all]) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /home/anmol/miniconda/envs/globalchem/lib/python3.10/site-packages/pytz-2022.1-py3.10.egg (from pandas->global-chem-extensions[forcefields]->global-chem[all]) (2022.1)
Collecting packaging>=16.8
  Using cached packaging-21.3-py3-none-any.whl (40 kB)
Collecting Jinja2>=2.9
  Using cached Jinja2-3.1.2-py3-none-any.whl (133 kB)
Collecting tornado>=5.1
  Using cached tornado-6.2-cp37-abi3-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl (423 kB)
Collecting typing-extensions>=3.10.0
  Using cached typing_extensions-4.3.0-py3-none-any.whl (25 kB)
Requirement already satisfied: pillow>=7.1.0 in /home/anmol/miniconda/envs/globalchem/lib/python3.10/site-packages/Pillow-9.2.0-py3.10-linux-x86_64.egg (from bokeh->global-chem-extensions[forcefields]->global-chem[all]) (9.2.0)
Collecting matplotlib>=3
  Using cached matplotlib-3.5.2-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (11.9 MB)
Collecting itsdangerous>=2.0
  Using cached itsdangerous-2.1.2-py3-none-any.whl (15 kB)
Collecting click>=8.0
  Using cached click-8.1.3-py3-none-any.whl (96 kB)
Collecting Werkzeug>=2.0
  Using cached Werkzeug-2.1.2-py3-none-any.whl (224 kB)
Collecting epam.indigo==1.4.0b0
  Using cached epam.indigo-1.4.0b0-py3-none-manylinux1_x86_64.whl (11.5 MB)
Collecting molpdf
  Using cached molpdf-0.4.2.tar.gz (11 kB)
  Preparing metadata (setup.py) ... done
  Using cached molpdf-0.4.0.tar.gz (10 kB)
  Preparing metadata (setup.py) ... done
  Using cached molpdf-0.3.0.tar.gz (8.1 kB)
  Preparing metadata (setup.py) ... done
  Using cached molpdf-0.2.6.tar.gz (8.0 kB)
  Preparing metadata (setup.py) ... done
  Using cached molpdf-0.2.5.tar.gz (8.0 kB)
  Preparing metadata (setup.py) ... done
  Using cached molpdf-0.2.4.tar.gz (8.0 kB)
  Preparing metadata (setup.py) ... done
  Using cached molpdf-0.2.2.tar.gz (8.0 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [12 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-relkp6an/molpdf_d670ec1d41774167a8d946a18fe7b5c1/setup.py", line 50, in <module>
          install_requires=_parse_requirements('requires.txt'),
        File "/tmp/pip-install-relkp6an/molpdf_d670ec1d41774167a8d946a18fe7b5c1/setup.py", line 28, in _parse_requirements
          return distutils.text_file.TextFile(filename=str(Path(__file__).with_name(filename))).readlines()
        File "/home/anmol/miniconda/envs/globalchem/lib/python3.10/site-packages/setuptools/_distutils/text_file.py", line 100, in __init__
          self.open(filename)
        File "/home/anmol/miniconda/envs/globalchem/lib/python3.10/site-packages/setuptools/_distutils/text_file.py", line 115, in open
          self.file = io.open(self.filename, 'r', errors=self.errors)
      FileNotFoundError: [Errno 2] No such file or directory: '/tmp/pip-install-relkp6an/molpdf_d670ec1d41774167a8d946a18fe7b5c1/requires.txt'
      [end of output]
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed
```
× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

**Comment by Sulstice** [comment]
Using cached of molpdf, maybe the molpdf setup is f'ed up. Let me investigate, been awhile....4-5 years ago.

**Comment by Sulstice** [comment]
Huh python 3.10? I wonder if that is the issue. requires.txt? That's misconfigured internally but not within my distribution layer:

https://github.com/Sulstice/molpdf/blob/master/setup.py

```
# requirements
# ------------
with open('requirements.txt') as f:
    REQUIREMENTS = f.read().strip().split('\n')
```

To setup your environment, you did conda with python 3.10. I heard a lot of packages started failing on that version

**Comment by anmolecule** [comment]
Are you sure this requirements.txt file is available in pip source directory of global-chem[all]

**Comment by anmolecule** [comment]
The problem exists for any python version. Although I have installed it differently by using setup.py inside global_chem_extensions, you should check if your pip upload has 'requirements.txt' / 'requires.txt' because it is a file outside the source directory. So you need to explicitly upload it.

**Comment by Sulstice** [comment]
I'm able to recreate, looks like the molpdf is caching down to its reduced version. Maybe when there was a bug? Something weird is going on here.

**Comment by Sulstice** [comment]
I think I resolved the MolPDF issue, try it again and find out. It might have been the dependencies being hardcoded into the molpdf and somewhere a long the distribution pipeline it has gotten confused, I think the requirements.txt file is a red herring.

**Comment by Sulstice** [comment]
This:

```
epam.indigo==1.4.0b0
numpy==1.18.3
opencv-python==4.2.0.34
pdfminer==20191125
pdfrw==0.4
Pillow==7.1.1
pycryptodome==3.9.7
reportlab==3.5.42
six==1.14.0
```

To this:

```
epam.indigo
numpy
opencv-python
pdfminer==20191125
pdfrw==0.4
Pillow==7.1.1
pycryptodome==3.9.7
reportlab==3.5.42
six
```
