### ISSUE TITLE
SS-42: Lost Support for the Windows Users

### ISSUE THREAD

**Issue by Sulstice** [Global-Chem/global-chem#86]
@dsipos05 Hey David, I lost support for windows users because there is a codex problem happening with a string character of mine in the main GlobalChem function that is apparently not read in windows machines but accepted in ubuntu and MacOS. This also didn't used to be the case and has recently occurred with the windows latest branch. 

Here is the bug stacktrace:

```
Test the intialize of the class, with parameters if it extends to that ... ok
Test the printing of the network ... ERROR
Test the Node Attribute to the GlobalChem Class ... ok
Test the Building of the GlobalChem Network ... ERROR
Test the fetching of all data ... ok
Fetch the Node Data and Test ... ERROR
Test the get and set of the nodes ... ERROR
Test the get of a node ... ERROR
Test the fetcher function for IUPAC by SMILES ... ok
Compute the Common Score of a molecule ... ok
Test the independent networks of user defined. ... ok
Test the deep layer network graphs ... ERROR

======================================================================
ERROR: Test the printing of the network
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\hostedtoolcache\windows\Python\3.8.[10](https://github.com/Sulstice/global-chem/runs/6134300824?check_suite_focus=true#step:5:10)\x64\lib\site-packages\nose\case.py", line 198, in runTest
    self.test(*self.arg)
  File "D:\a\global-chem\global-chem\global_chem\tests\test_global_chem.py", line 31, in test_print_network
    gc.print_globalchem_network()
  File "D:\a\global-chem\global-chem\global_chem\global_chem\global_chem.py", line 1090, in print_globalchem_network
    print(PrintTreeUtilities.printTrees(_PRINT_NODE_KEY['global_chem']))
KeyError: 'global_chem'

======================================================================
ERROR: Test the Building of the GlobalChem Network
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\site-packages\nose\case.py", line 198, in runTest
    self.test(*self.arg)
  File "D:\a\global-chem\global-chem\global_chem\tests\test_global_chem.py", line 57, in test_build_global_chem_network
    molecules = gc.get_node_smiles('emerging_perfluoroalkyls')
  File "D:\a\global-chem\global-chem\global_chem\global_chem\global_chem.py", line 664, in get_node_smiles
    raise GraphNetworkError(
global_chem.global_chem.GraphNetworkError: No Node named emerging_perfluoroalkyls exists

======================================================================
ERROR: Fetch the Node Data and Test
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\site-packages\nose\case.py", line 198, in runTest
    self.test(*self.arg)
  File "D:\a\global-chem\global-chem\global_chem\tests\test_global_chem.py", line 91, in test_fetch_node_data
    smiles = gc.get_node_smiles('emerging_perfluoroalkyls')
  File "D:\a\global-chem\global-chem\global_chem\global_chem\global_chem.py", line 664, in get_node_smiles
    raise GraphNetworkError(
global_chem.global_chem.GraphNetworkError: No Node named emerging_perfluoroalkyls exists

======================================================================
ERROR: Test the get and set of the nodes
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\site-packages\nose\case.py", line 198, in runTest
    self.test(*self.arg)
  File "D:\a\global-chem\global-chem\global_chem\tests\test_global_chem.py", line 108, in test_get_and_set_node_values
    gc.set_node_value('emerging_perfluoroalkyls', {'some_data': ['bunny']})
  File "D:\a\global-chem\global-chem\global_chem\global_chem\global_chem.py", line 940, in set_node_value
    raise GraphNetworkError(
global_chem.global_chem.GraphNetworkError: No Node named emerging_perfluoroalkyls exists

======================================================================
ERROR: Test the get of a node
----------------------------------------------------------------------
Traceback (most recent call last):
  File "D:\a\global-chem\global-chem\global_chem\global_chem\global_chem.py", line 639, in get_node
    node = self.network[name]
KeyError: 'emerging_perfluoroalkyls'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\a\global-chem\global-chem\global_chem\global_chem\global_chem.py", line 642, in get_node
    node = self.network[python_name]
KeyError: 'emerging_perfluoroalkyls.py'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\site-packages\nose\case.py", line 198, in runTest
    self.test(*self.arg)
  File "D:\a\global-chem\global-chem\global_chem\tests\test_global_chem.py", line 139, in test_get_node
    node = gc.get_node('emerging_perfluoroalkyls')
  File "D:\a\global-chem\global-chem\global_chem\global_chem\global_chem.py", line 644, in get_node
    raise GraphNetworkError(
global_chem.global_chem.GraphNetworkError: No Node named emerging_perfluoroalkyls exists

======================================================================
ERROR: Test the deep layer network graphs
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\site-packages\nose\case.py", line 198, in runTest
    self.test(*self.arg)
  File "D:\a\global-chem\global-chem\global_chem\tests\test_global_chem.py", line 224, in test_deep_layer_networks
    gc.print_deep_network()
  File "D:\a\global-chem\global-chem\global_chem\global_chem\global_chem.py", line [11](https://github.com/Sulstice/global-chem/runs/6134300824?check_suite_focus=true#step:5:11)27, in print_deep_network
    print(PrintTreeUtilities.printTrees(_DEEP_NETWORK_KEY[ self.root_node ]))
  File "D:\a\global-chem\global-chem\global_chem\global_chem\global_chem.py", line 277, in printTrees
    print("\n".join(get_repr(node)))
  File "C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\encodings\cp[12](https://github.com/Sulstice/global-chem/runs/6134300824?check_suite_focus=true#step:5:12)52.py", line [19](https://github.com/Sulstice/global-chem/runs/6134300824?check_suite_focus=true#step:5:19), in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\u[25](https://github.com/Sulstice/global-chem/runs/6134300824?check_suite_focus=true#step:5:25)0c' in position [38](https://github.com/Sulstice/global-chem/runs/6134300824?check_suite_focus=true#step:5:38): character maps to <undefined>
```

It's running a pytest and basically hangs up on this character:

```
'charmap' codec can't encode character '\u[25]
```

Where it's referrering to this function:

https://github.com/Sulstice/global-chem/blob/master/global_chem/global_chem/global_chem.py

```
        # prepend connectors
        if startingFanIndex == endingFanIndex:
            return lst
        for i in range(len(lst)):
            if i == startingFanIndex:
                lst[i] = "┌%s" % lst[i]
```

And then it won't load anything else because apparently this function. 

To recreate the issue edit this file:

https://github.com/Sulstice/global-chem/blob/master/.github/workflows/continous_integration.yml

Convert 

```
        os: ["ubuntu-latest", "macos-latest"]
```

To 

```

        os: ["ubuntu-latest", "windows-latest", "macos-latest"]
```

Is that enough to go on?

**Comment by Sulstice** [comment]
Problem still persists, even with the cleanup of the bug in version 1.6.0.9. Mostly comes from the intial building of the network and windows's inability to process the fstring in the PrintUtilitiesTree function perhaps.

**Comment by Sulstice** [comment]
It was a file path to deal with windows, also python windows connection requires the stdin and stdout to be configured with utf-8 encoding. Solved.
